apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-valkey-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: valkey
    spec:
      containers:
      - name: ccs3-valkey-container
        image: valkey/valkey:8.0.1-alpine3.20
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-state-manager-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: state-manager
    spec:
      containers:
      - name: ccs3-state-manager-container
        image: ccs3/state-manager:latest
        env:
        - name: CCS3_REDIS_HOST
          value: "ccs3-redis-service"
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-pc-connector-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: pc-connector
    spec:
      containers:
      - name: ccs3-pc-connector-container
        image: ccs3/pc-connector:latest
        env:
        - name: CCS3_REDIS_HOST
          value: "ccs3-redis-service"
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-operator-connector-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: operator-connector
    spec:
      containers:
      - name: ccs3-operator-connector-container
        image: ccs3/operator-connector:latest
        env:
        - name: CCS3_REDIS_HOST
          value: "ccs3-redis-service"
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"

---

apiVersion: v1
kind: Service
metadata:
  name: ccs3-redis-service
  labels:
    app: ccs3
    service: ccs3-redis-service
spec:
  type: ClusterIP
  ports:
    - name: redis-backend
      protocol: TCP
      port: 6379
    #   targetPort: 6379
  selector:
    app: ccs3
    pod: redis

---

apiVersion: v1
kind: Service
metadata:
  name: ccs3-pc-connector-service
  labels:
    app: ccs3
    service: ccs3-pc-connector-service
spec:
  type: LoadBalancer
  ports:
    - name: pc-connector-backend
      protocol: TCP
      port: 65502
      # targetPort: 6379
  selector:
    app: ccs3
    pod: pc-connector