apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-static-files-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: ccs3-static-files
    spec:
      containers:
      - name: ccs3-static-files-container
        image: ccs3/static-files-service:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: nginx-certs-volume
          mountPath: /etc/ssl/nginx-certs
        resources:
          limits:
            memory: 32Mi
            cpu: "0.1"
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /health-check.txt
            port: 443
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 3
      volumes:
      - name: nginx-certs-volume
        secret:
          secretName: nginx-certs

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-valkey-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: valkey
    spec:
      containers:
      - name: ccs3-valkey-container
        image: valkey/valkey:8.1.1-alpine3.21
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-state-manager-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: state-manager
    spec:
      containers:
      - name: ccs3-state-manager-container
        image: ccs3/state-manager:latest
        imagePullPolicy: Never
        env:
        - name: CCS3_STATE_MANAGER_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: storage-connection-string
              key: conn-string
        - name: CCS3_STATE_MANAGER_STORAGE_PROVIDER_DATABASE_MIGRATION_SCRIPTS_DIRECTORY
          valueFrom:
            secretKeyRef:
              name: state-manager-storage-provider-database-migration-scripts-directory
              key: path
        - name: CCS3_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: host
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-pc-connector-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: pc-connector
    spec:
      containers:
      - name: ccs3-pc-connector-container
        image: ccs3/pc-connector:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: pc-connector-certs-volume
          mountPath: /app/dist/certificates
        env:
        - name: CCS3_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: host
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"
      volumes:
      - name: pc-connector-certs-volume
        secret:
          secretName: pc-connector-certs

---

apiVersion: v1
kind: Service
metadata:
  name: ccs3-pc-connector-load-balancer
  labels:
    app: ccs3
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - name: ccs3-pc-connector-port
    protocol: TCP
    port: 65501
  selector:
   app: ccs3
   pod: pc-connector

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-operator-connector-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: operator-connector
    spec:
      containers:
      - name: ccs3-operator-connector-container
        image: ccs3/operator-connector:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: operator-connector-certs-volume
          mountPath: /app/dist/certificates
        env:
        - name: CCS3_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: host
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"
      volumes:
      - name: operator-connector-certs-volume
        secret:
          secretName: operator-connector-certs

---

apiVersion: v1
kind: Service
metadata:
  name: ccs3-operator-connector-load-balancer
  labels:
    app: ccs3
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - name: ccs3-operator-connector-port
    protocol: TCP
    port: 65502
  selector:
   app: ccs3
   pod: operator-connector

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccs3-qrcode-signin-deployment
  labels:
    app: ccs3
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccs3
  template:
    metadata:
      labels:
        app: ccs3
        pod: qrcode-signin
    spec:
      containers:
      - name: ccs3-qrcode-signin-container
        image: ccs3/qrcode-signin:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: qrcode-signin-certs-volume
          mountPath: /app/dist/certificates
        env:
        - name: CCS3_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: host
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"
      volumes:
      - name: qrcode-signin-certs-volume
        secret:
          secretName: qrcode-signin-certs

---

apiVersion: v1
kind: Service
metadata:
  name: ccs3-qrcode-signin-load-balancer
  labels:
    app: ccs3
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - name: ccs3-qrcode-signin-port
    protocol: TCP
    port: 65503
  selector:
   app: ccs3
   pod: qrcode-signin

---

apiVersion: v1
kind: Service
metadata:
  name: ccs3-valkey-service
  labels:
    app: ccs3
    service: ccs3-valkey-service
    tier: backend
spec:
  type: ClusterIP
  ports:
    - name: valkey-backend
      protocol: TCP
      port: 6379
    #   targetPort: 6379
  selector:
    app: ccs3
    pod: valkey

---

apiVersion: v1
kind: Service
metadata:
  name: ccs3-static-files-service-load-balancer
  labels:
    app: ccs3
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - name: ccs3-static-files-service-port
    protocol: TCP
    port: 65500
    targetPort: 443
  selector:
   app: ccs3
   pod: ccs3-static-files
