ARG TAG=dev
ARG IMAGE_PREFIX=docker.io/computerclubsystem
ARG CLIENTAPP_IMAGE=${IMAGE_PREFIX}/client-app:${TAG}
ARG CLIENTAPPWINDOWSSERVICE_IMAGE=${IMAGE_PREFIX}/client-app-windows-service:${TAG}
ARG CLIENTAPPBOOTSTRAPWINDOWSSERVICE_IMAGE=${IMAGE_PREFIX}/client-app-bootstrap-windows-service:${TAG}

FROM ${CLIENTAPP_IMAGE} AS clientapp_image
FROM scratch AS clientapp_image_clean
COPY --from=clientapp_image / /
FROM ${CLIENTAPPWINDOWSSERVICE_IMAGE} AS clientappwindowsservice_image
FROM scratch AS clientappwindowsservice_image_clean
COPY --from=clientappwindowsservice_image / /
FROM ${CLIENTAPPBOOTSTRAPWINDOWSSERVICE_IMAGE} AS clientappbootstrapwindowsservice_image
FROM scratch AS clientappbootstrapwindowsservice_image_clean
COPY --from=clientappbootstrapwindowsservice_image / /

# Copy the files and create necessary .zip
FROM alpine AS packer
WORKDIR /app
COPY --from=clientapp_image_clean app/dist ccs3-client-apps/ccs3-client-app-windows-service/Ccs3ClientApp
COPY --from=clientappwindowsservice_image_clean app/dist ccs3-client-apps/ccs3-client-app-windows-service
COPY --from=clientappbootstrapwindowsservice_image_clean app/dist ccs3-client-apps/ccs3-client-app-bootstrap-windows-service
RUN apk add --no-cache zip \
    && cd /app/ccs3-client-apps/ccs3-client-app-windows-service \
    && zip -r /app/ccs3-client-apps/ccs3-client-app-windows-service/Ccs3ClientAppWindowsService.zip .
RUN sha512sum ccs3-client-apps/ccs3-client-app-windows-service/Ccs3ClientAppWindowsService.exe > ccs3-client-apps/ccs3-client-app-windows-service/ccs3-client-files-checksums.sha
RUN sha512sum ccs3-client-apps/ccs3-client-app-windows-service/Ccs3ClientApp/Ccs3ClientApp.exe >> ccs3-client-apps/ccs3-client-app-windows-service/ccs3-client-files-checksums.sha
RUN cd /app/ccs3-client-apps/ccs3-client-app-bootstrap-windows-service \
   && zip -r /app/ccs3-client-apps/ccs3-client-app-bootstrap-windows-service/Ccs3ClientAppBootstrapWindowsService.zip .
RUN mkdir /app/ccs3-client-apps/dist \
    && cp /app/ccs3-client-apps/ccs3-client-app-windows-service/Ccs3ClientAppWindowsService.zip /app/ccs3-client-apps/dist \
    && cp /app/ccs3-client-apps/ccs3-client-app-windows-service/ccs3-client-files-checksums.sha /app/ccs3-client-apps/dist \
    && cp /app/ccs3-client-apps/ccs3-client-app-bootstrap-windows-service/Ccs3ClientAppBootstrapWindowsService.zip /app/ccs3-client-apps/dist


# Keep nginx:1.27.x - Nginx version 1.29+ uses newer OpelSSL version which break httpClient.GetStringAsync calls from .NET code for small files
# The .NET clients should use GetStreamAsync instead and then the nginx version could be updated
FROM nginx:1.27.3-alpine-slim
COPY nginx.conf /etc/nginx
COPY health-check.txt /usr/share/nginx/html
COPY --from=packer /app/ccs3-client-apps/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
