# Build for Rancher with containerd: nerdctl -n k8s.io build -t ccs3/state-manager:latest -f Dockerfile.state-manager ../
FROM node:20.11.0-alpine3.19 AS build

WORKDIR /app

COPY libs/types ./libs/types
COPY libs/redis-client ./libs/redis-client
COPY apps/state-manager ./apps/state-manager
COPY package-lock.json .
COPY package.json .
# TODO: Installation should also install dependencies in node_modules - this one uses symlinks causing the dependencies folders like libs/redis-client mandatory
#       Need to investigate "npm install --install-links"
RUN npm run apps/state-manager:build-include-deps
COPY apps/state-manager/src/postgre-storage/database-migrations ./apps/state-manager/dist/postgre-storage/database-migrations/ 
