import { OperatorRequestMessageType } from '@computerclubsystem/types/messages/operators/declarations/operator-message-type.mjs';
import { OperatorRequestMessageHandler } from './declarations.mjs';
import { AuthRequestMessageHandler } from './operator-request-message-handlers/auth.mjs';
import { ShutdownDevicesRequestMessageHandler } from './operator-request-message-handlers/shutdown-devices.mjs';
import { GetDeviceConnectivityDetailsRequestMessageHandler } from './operator-request-message-handlers/get-device-connectivity-details.mjs';
import { GetTariffDeviceGroupsRequestMessageHandler } from './operator-request-message-handlers/get-tariff-device-groups.mjs';
import { RestartDevicesRequestMessageHandler } from './operator-request-message-handlers/restart-devices.mjs';
import { ShutdownStoppedRequestMessageHandler } from './operator-request-message-handlers/shutdown-stopped.mjs';
import { FilterServerLogsRequestMessageHandler } from './operator-request-message-handlers/filter-server-logs.mjs';
import { GetDeviceCompletedSessionsRequestMessageHandler } from './operator-request-message-handlers/get-device-completed-sessions.mjs';
import { SetDeviceStatusNoteRequestMessageHandler } from './operator-request-message-handlers/set-device-status-note.mjs';
import { GetAllAllowedDeviceObjectsRequestMessageHandler } from './operator-request-message-handlers/get-all-allowed-device-objects.mjs';
import { UpdateDeviceGroupRequestMessageHandler } from './operator-request-message-handlers/update-device-group.mjs';
import { CreateDeviceGroupRequestMessageHandler } from './operator-request-message-handlers/create-device-group.mjs';
import { GetDeviceGroupDataRequestMessageHandler } from './operator-request-message-handlers/get-device-group-data.mjs';
import { GetAllDeviceGroupsRequestMessageHandler } from './operator-request-message-handlers/get-all-device-groups.mjs';
import { UpdateProfileSettingsRequestMessageHandler } from './operator-request-message-handlers/update-profile-settings.mjs';
import { GetProfileSettingsRequestMessageHandler } from './operator-request-message-handlers/get-profile-settings.mjs';
import { ChangePasswordRequestMessageHandler } from './operator-request-message-handlers/change-password.mjs';
import { CreateDeviceRequestMessageHandler } from './operator-request-message-handlers/create-device.mjs';
import { UpdateSystemSettingsValuesRequestMessageHandler } from './operator-request-message-handlers/update-system-settings-values.mjs';
import { GetAllSystemSettingsRequestMessageHandler } from './operator-request-message-handlers/get-all-system-settings.mjs';
import { GetShiftsRequestMessageHandler } from './operator-request-message-handlers/get-shifts.mjs';
import { CompleteShiftRequestMessageHandler } from './operator-request-message-handlers/complete-shift.mjs';
import { GetCurrentShiftStatusRequestMessageHandler } from './operator-request-message-handlers/get-current-shift-status.mjs';
import { GetSignedInUsersRequestMessageHandler } from './operator-request-message-handlers/get-signed-in-users.mjs';
import { RechargeTariffDurationRequestMessageHandler } from './operator-request-message-handlers/recharge-tariff-duration.mjs';
import { DeleteDeviceContinuationRequestMessageHandler } from './operator-request-message-handlers/delete-device-continuation.mjs';
import { CreateDeviceContinuationRequestMessageHandler } from './operator-request-message-handlers/create-device-continuation.mjs';
import { TransferDeviceRequestMessageHandler } from './operator-request-message-handlers/transfer-device.mjs';
import { StopDeviceRequestMessageHandler } from './operator-request-message-handlers/stop-device.mjs';
import { UpdateUserWithRolesRequestMessageHandler } from './operator-request-message-handlers/update-user-with-roles.mjs';
import { CreateUserWithRolesRequestMessageHandler } from './operator-request-message-handlers/create-user-with-roles.mjs';
import { GetUserWithRolesRequestMessageHandler } from './operator-request-message-handlers/get-user-with-roles.mjs';
import { GetAllUsersRequestMessageHandler } from './operator-request-message-handlers/get-all-users.mjs';
import { CreateRoleWithPermissionsRequestMessageHandler } from './operator-request-message-handlers/create-role-with-permissions.mjs';
import { UpdateRoleWithPermissionsRequestMessageHandler } from './operator-request-message-handlers/update-role-with-permissions.mjs';
import { GetAllPermissionsRequestMessageHandler } from './operator-request-message-handlers/get-all-permissions.mjs';
import { GetRoleWithPermissionsRequestMessageHandler } from './operator-request-message-handlers/get-role-with-permissions.mjs';
import { GetAllRolesRequestMessageHandler } from './operator-request-message-handlers/get-all-roles.mjs';
import { StartDeviceRequestMessageHandler } from './operator-request-message-handlers/start-device.mjs';
import { GetTariffByIdRequestMessageHandler } from './operator-request-message-handlers/get-tariff-by-id.mjs';
import { CreatePrepaidTariffRequestMessageHandler } from './operator-request-message-handlers/create-prepaid-tariff.mjs';
import { CreateTariffRequestMessageHandler } from './operator-request-message-handlers/create-tariff.mjs';
import { UpdateTariffRequestMessageHandler } from './operator-request-message-handlers/update-tariff.mjs';
import { GetAllTariffsRequestMessageHandler } from './operator-request-message-handlers/get-all-tariffs.mjs';
import { CreateSignInCodeRequestMessageHandler } from './operator-request-message-handlers/create-sign-in-code.mjs';
import { GetAllDevicesRequestMessageHandler } from './operator-request-message-handlers/get-all-devices.mjs';
import { GetDeviceByIdRequestMessageHandler } from './operator-request-message-handlers/get-device-by-id.mjs';
import { RefreshTokenRequestMessageHandler } from './operator-request-message-handlers/refresh-token.mjs';
import { SignOutRequestMessageHandler } from './operator-request-message-handlers/sign-out.mjs';
import { UpdateDeviceRequestMessageHandler } from './operator-request-message-handlers/update-device.mjs';
import { GetTariffCurrentUsageRequestMessageHandler } from './operator-request-message-handlers/get-tariff-current-usage.mjs';

export class RequestMessageHandlerHelper {
    createOperatorRequestMessageHandlersMap(): Map<OperatorRequestMessageType, OperatorRequestMessageHandler> {
        const map = new Map<OperatorRequestMessageType, OperatorRequestMessageHandler>();
        map.set(OperatorRequestMessageType.authRequest, new AuthRequestMessageHandler());
        map.set(OperatorRequestMessageType.shutdownDevicesRequest, new ShutdownDevicesRequestMessageHandler());
        map.set(OperatorRequestMessageType.getDeviceConnectivityDetailsRequest, new GetDeviceConnectivityDetailsRequestMessageHandler());
        map.set(OperatorRequestMessageType.getTariffDeviceGroupsRequest, new GetTariffDeviceGroupsRequestMessageHandler());
        map.set(OperatorRequestMessageType.restartDevicesRequest, new RestartDevicesRequestMessageHandler());
        map.set(OperatorRequestMessageType.shutdownStoppedRequest, new ShutdownStoppedRequestMessageHandler());
        map.set(OperatorRequestMessageType.filterServerLogsRequest, new FilterServerLogsRequestMessageHandler());
        map.set(OperatorRequestMessageType.getDeviceCompletedSessionsRequest, new GetDeviceCompletedSessionsRequestMessageHandler());
        map.set(OperatorRequestMessageType.setDeviceStatusNoteRequest, new SetDeviceStatusNoteRequestMessageHandler());
        map.set(OperatorRequestMessageType.getAllAllowedDeviceObjectsRequest, new GetAllAllowedDeviceObjectsRequestMessageHandler());
        map.set(OperatorRequestMessageType.updateDeviceGroupRequest, new UpdateDeviceGroupRequestMessageHandler());
        map.set(OperatorRequestMessageType.createDeviceGroupRequest, new CreateDeviceGroupRequestMessageHandler());
        map.set(OperatorRequestMessageType.getDeviceGroupDataRequest, new GetDeviceGroupDataRequestMessageHandler());
        map.set(OperatorRequestMessageType.getAllDeviceGroupsRequest, new GetAllDeviceGroupsRequestMessageHandler());
        map.set(OperatorRequestMessageType.updateProfileSettingsRequest, new UpdateProfileSettingsRequestMessageHandler());
        map.set(OperatorRequestMessageType.getProfileSettingsRequest, new GetProfileSettingsRequestMessageHandler());
        map.set(OperatorRequestMessageType.changePasswordRequest, new ChangePasswordRequestMessageHandler());
        map.set(OperatorRequestMessageType.createDeviceRequest, new CreateDeviceRequestMessageHandler());
        map.set(OperatorRequestMessageType.updateDeviceRequest, new UpdateDeviceRequestMessageHandler());
        map.set(OperatorRequestMessageType.updateSystemSettingsValuesRequest, new UpdateSystemSettingsValuesRequestMessageHandler());
        map.set(OperatorRequestMessageType.getAllSystemSettingsRequest, new GetAllSystemSettingsRequestMessageHandler());
        map.set(OperatorRequestMessageType.getShifts, new GetShiftsRequestMessageHandler());
        map.set(OperatorRequestMessageType.completeShiftRequest, new CompleteShiftRequestMessageHandler());
        map.set(OperatorRequestMessageType.getCurrentShiftStatusRequest, new GetCurrentShiftStatusRequestMessageHandler());
        map.set(OperatorRequestMessageType.getSignedInUsersRequest, new GetSignedInUsersRequestMessageHandler());
        map.set(OperatorRequestMessageType.rechargeTariffDurationRequest, new RechargeTariffDurationRequestMessageHandler());
        map.set(OperatorRequestMessageType.deleteDeviceContinuationRequest, new DeleteDeviceContinuationRequestMessageHandler());
        map.set(OperatorRequestMessageType.createDeviceContinuationRequest, new CreateDeviceContinuationRequestMessageHandler());
        map.set(OperatorRequestMessageType.transferDeviceRequest, new TransferDeviceRequestMessageHandler());
        map.set(OperatorRequestMessageType.stopDeviceRequest, new StopDeviceRequestMessageHandler());
        map.set(OperatorRequestMessageType.updateUserWithRolesRequest, new UpdateUserWithRolesRequestMessageHandler());
        map.set(OperatorRequestMessageType.createUserWithRolesRequest, new CreateUserWithRolesRequestMessageHandler());
        map.set(OperatorRequestMessageType.getUserWithRolesRequest, new GetUserWithRolesRequestMessageHandler());
        map.set(OperatorRequestMessageType.getAllUsersRequest, new GetAllUsersRequestMessageHandler());
        map.set(OperatorRequestMessageType.createRoleWithPermissionsRequest, new CreateRoleWithPermissionsRequestMessageHandler());
        map.set(OperatorRequestMessageType.updateRoleWithPermissionsRequest, new UpdateRoleWithPermissionsRequestMessageHandler());
        map.set(OperatorRequestMessageType.getAllPermissionsRequest, new GetAllPermissionsRequestMessageHandler());
        map.set(OperatorRequestMessageType.getRoleWithPermissionsRequest, new GetRoleWithPermissionsRequestMessageHandler());
        map.set(OperatorRequestMessageType.getAllRolesRequest, new GetAllRolesRequestMessageHandler());
        map.set(OperatorRequestMessageType.startDeviceRequest, new StartDeviceRequestMessageHandler());
        map.set(OperatorRequestMessageType.getTariffByIdRequest, new GetTariffByIdRequestMessageHandler());
        map.set(OperatorRequestMessageType.createPrepaidTariffRequest, new CreatePrepaidTariffRequestMessageHandler());
        map.set(OperatorRequestMessageType.createTariffRequest, new CreateTariffRequestMessageHandler());
        map.set(OperatorRequestMessageType.updateTariffRequest, new UpdateTariffRequestMessageHandler());
        map.set(OperatorRequestMessageType.getAllTariffsRequest, new GetAllTariffsRequestMessageHandler());
        map.set(OperatorRequestMessageType.createSignInCodeRequest, new CreateSignInCodeRequestMessageHandler());
        map.set(OperatorRequestMessageType.getAllDevicesRequest, new GetAllDevicesRequestMessageHandler());
        map.set(OperatorRequestMessageType.getDeviceByIdRequest, new GetDeviceByIdRequestMessageHandler());
        map.set(OperatorRequestMessageType.refreshTokenRequest, new RefreshTokenRequestMessageHandler());
        map.set(OperatorRequestMessageType.signOutRequest, new SignOutRequestMessageHandler());
        map.set(OperatorRequestMessageType.getTariffCurrentUsageRequest, new GetTariffCurrentUsageRequestMessageHandler());

        return map;
    }
}