export const envVars = {
    CCS3_REDIS_HOST: 'CCS3_REDIS_HOST',
    CCS3_REDIS_PORT: 'CCS3_REDIS_PORT',
    CCS3_OPERATOR_CONNECTOR_STATIC_FILES_PATH: 'CCS3_OPERATOR_CONNECTOR_STATIC_FILES_PATH',
    CCS3_OPERATOR_CONNECTOR_NO_STATIC_FILES_SERVING: 'CCS3_OPERATOR_CONNECTOR_NO_STATIC_FILES_SERVING',
};
